---
image: ubuntu:18.04

plain_build:
  before_script:
    - apt-get update -y -qq
    - apt-get install -y -q --no-install-recommends cmake make
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make -j$(nproc --ignore=1)
