---
image: ubuntu:18.04

plain_build:
  before_script:
    - apt-get update -y -q
    - apt-get install -y -q --no-install-recommends cmake make
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make -j$(nproc --ignore=1)
  except:
    variables:
      - $CI_REGISTRY

image_build:
  image: $CI_REGISTRY_IMAGE
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make -j$(nproc --ignore=1)
  only:
    variables:
      - $CI_REGISTRY
